language: go
go:
  - 1.2
  - tip
before_script:
  - curl -s -I -L https://gocover.io/_/github.com/gomicro/postal
script:
  - go test -v $(go list ./... | grep -v /vendor/)
notifications:
  slack:
    secure: KuuDwtXV/oWKzjOmcRzFXR7qUKoORXOrxlJMUPM9c1DtnKZUO1H4FlEpQETdbrfyGhg1rYJLwcOiFpKDngcsIRzyBu3/2bn9z8b0RESUG3+vnGl6hPshJe4taIO5cYkZownU/xW+IxlQbJh9prW32Xzbi9Pnt6N0nB2XkeIhE6bUKzqQrDF8JEN2CurFOh9AraXCmVAU/YsKRgnuWS1wiRV54T376YXJ4vAryA+9hlwXLYghdLL2WxrdPQEBrk87qFxDDGwVz2EUqPK/t/NC9aezZOowTuWJtjvnnKYitWyXJqdA74npcBBTDSK5q0CRjxYWSOkUcOomNn7vC6/lnKS4EdDs/PDwhHdDNF6oVMrDpuFXKEgcN71YX5eW3NtxvcgatbQkh4AVjQTp+h0B/CGilNrPNfyGjFOP9k1rN09PC4QmIMcPQs3AVkisMqBU2UKs/JYUHAhmRWjn+uakNBQA4lTcqdPe2fRjz68tRSixKT7eCPShC9+QjLwVDjIf6EvYtx+IXhob0biultVGfzwEmOHEjAe2LS8GDb1Eh2wKUvz+B0GOaxxhuEBlWeWUT9gYadpDRPqlOfjIzAdwTp8eb/fkOwWOUqqP+mecauFqonQSWqdVTh80enZZm5GmWZjSdQjdaLcj34w6tbTgeCxi4H+z/qaOOGHuffh2i54=
